<?php

namespace Database\Seeders;

use App\Models\Material;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Material::insert([
            [
                "name" => "Boitier - 1 Caméra Panasonic Lumix DC-GH5 Mirrorless Micro Four Thirds . ",
                "reference" => "DC-GH5KBODY",
                "quantite" => 2,
                "type" => "camera",
                "image" => "material1.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "MEDIUM 12-35mm (O58mm) Caméra Panasonic Lumix G X Vario 12-35mm f/2.8 II ASPH. POWER O.I.S",
                "reference" => "H-HSA12035",
                "type" => "camera",
                "quantite" => 1,
                "image" => "material2.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],

            [
                "name" => "CLOSE-UP 35-100mm (O58 mm) Caméra Panasonic Lumix G X Vario 35-100mm f/2.8 II POWER O.I.S.",
                "reference" => "H-HSA35100",
                "type" => "camera",
                "quantite" => 1,
                "image" => "material3.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],

            [
                "name" => "SanDisk 64GB Extreme PRO UHS-II SDXC Memory Card.",
                "reference" => "SDSDXPK-064G-ANCIN",
                "type" => "autres",
                "quantite" => 5,
                "image" => "material4.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Trépied Caméra Studio.",
                "reference" => "Manfrotto 504HD",
                "type" => "camera",
                "quantite" => 2,
                "image" => "material5.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Lecteur de carte Lexar Professional USB 3.0.",
                "reference" => "Dual-Slot Reader (UDMA 7)",
                "type" => "autres",
                "quantite" => 1,
                "image" => "material6.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Panasonic DMW-BLF19 Rechargeable.",
                "reference" => "Lithium-ion Battery Pack (7.2V, 1860mAh)",
                "type" => "autres",
                "quantite" => 2,
                "image" => "material7.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Stabilisateur Mobile",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material8.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Boitier - 1 DJI Stabilisateur 3 axes pour smartphones. ",
                "reference" => "DC-GH5KBODY",
                "type" => "autres",
                "quantite" => 2,
                "image" => "material9.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Caméra portable DJI Pocket",
                "reference" => null,
                "type" => "camera",
                "quantite" => 1,
                "image" => "material10.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Microcravate Rode + une rallonge.",
                "reference" => null,
                "type" => "micro",
                "quantite" => 2,
                "image" => "material11.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Adapteur Lighting JACK",
                "reference" => null,
                "type" => "light",
                "quantite" => 2,
                "image" => "material12.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Caméra Photo Vidéo Eclairage Kit",
                "reference" => null,
                "type" => "camera",
                "quantite" => 1,
                "image" => "material13.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Zoom H6 Handy Recorder with Interchangeable Microphone System",
                "reference" => null,
                "type" => "micro",
                "quantite" => 1,
                "image" => "material14.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Micro-Cravate SENNHEISER Portable sans fil G4",
                "reference" => "EW 112P G4-B (626 - 668 MHz)",
                "type" => "casque",
                "quantite" => 4,
                "image" => "material15.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Audio-Technica Casque de monitoring fermé dynamique.",
                "reference" => "ATH-M20X",
                "type" => "casque",
                "quantite" => 4,
                "image" => "material16.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Audio-Technica Microphone - Microphone à condensateur à directivité variable",
                "reference" => "AT2050",
                "type" => "micro",
                "quantite" => 4,
                "image" => "material17.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Bras Pied de micro Bureau Suspension Boom Mic cisaillement Bras avec table Clip Microphone Support de montage Filtre anti-bruit Kit Noir Pare-brise",
                "reference" => null,
                "type" => "micro",
                "quantite" => 4,
                "image" => "material18.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Carte micro Kingston SDCX10/64GB",
                "reference" => null,
                "type" => "micro",
                "quantite" => 4,
                "image" => "material19.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "NANGUANG LED Lumière Studio Kit.",
                "reference" => "NANGUANG CN-30F+CN-600SA Studio",
                "type" => "light",
                "quantite" => 1,
                "image" => "material20.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Savage Widetone Seamless Background Paper (#75 True green, m 3,500 x  m 2,7)",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material21.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Savage Widetone Seamless Background Paper (#70 Storm White, m 3,500 x  m 2,7)",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material22.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Savage Widetone Seamless Background Paper (#43 Marmalade, m 3,500 x  m 2,7)",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material23.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Savage Widetone Seamless Background Paper (#29 Orchid, m 3,500 x  m 2,7)",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material24.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "Background Holder ",
                "reference" => null,
                "type" => "autres",
                "quantite" => 1,
                "image" => "material25.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
            [
                "name" => "BLACKMAGIC DESIGN ATEM MINI Pro - Mélangeur",
                "reference" => null,
                "type" => "micro",
                "quantite" => 1,
                "image" => "material26.jpg",
                "nombre_utilisation" => 0,
                "disponible" => true,
            ],
        ]);
    }
}
